# Generated by Django 5.0.1 on 2024-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
